name: ci-package-schema

on:
  pull_request:
    branches: ['main']
    paths:
      - 'packages/schemas/**'
      - '.github/workflows/ci-package-schema.yml'
  
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/schemas
        
    steps:
      - uses: actions/checkout@v5

      - name: Enable corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'
          cache-dependency-path: packages/schemas/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Run pre-commit checks
        run: pnpm run precommit